
import { Navbar } from "../../components";
import { Providers } from "../store/Providers";
import MainStyle from './MainStyle';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar />
      <MainStyle>
        <main className="w-100 mx-auto">
          <Providers>
            {children}
          </Providers>
        </main>
      </MainStyle>
    </>
  )
}
